In [37]:
import datetime
import functools
import itertools
import operator
import os
import math
import numpy as np
import pandas as pd
import string

### 1. Multiples of 3 and 5
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [2]:
sum([i for i in range(1, 1000) if i % 3 == 0 or i % 5 == 0])

233168

### 2. Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [98]:
def fibonacci(threshold: int):
    """Returns all Fibonacci numbers below a threshold"""
    this_num, next_num = 1, 2
    fibonacci_list = [this_num, next_num]
    while next_num <= threshold:
        this_num, next_num = next_num, this_num + next_num
        fibonacci_list += [next_num]
    return fibonacci_list[:-1]
sum([i for i in fibonacci(4000000) if i % 2 == 0])

4613732

### 3. Largest prime factor
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [8]:
def prime_factors(n: int):
    """Returns prime factors of a number as a list of integers"""
    assert n >= 1
    i = 2
    factors = []
    while i * i <= n:
        if n % i:
            i = i + 1
        else:
            n = n // i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors

prime_factors(600851475143)

[71, 839, 1471, 6857]

### 4. Largest palindrome product
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is $9009 = 91 × 99$.

Find the largest palindrome made from the product of two 3-digit numbers.

In [25]:
def is_palindrome(integer):
    string = str(integer)
    return string == string[::-1]

max_palindrome = 0
for i in range(100, 1000):
    for j in range(100, 1000):
        if is_palindrome(i * j) and i * j > max_palindrome:
            max_palindrome = i * j
    
print(max_palindrome)

906609

In [1]:
def is_palindrome(n):
    """Checks if a number n is a palindrome"""
    return str(n) == str(n)[::-1]
products = [pair[0] * pair[1] for pair in itertools.combinations(range(100, 999), 2)]
palindromes = [product for product in products if is_palindrome(product)]
max(palindromes)

906609

### 5. Smallest multiple

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [26]:
def value_counts(list_in):
    """Returns counts of elements in a list as a dict with values as keys and counts as values"""
    counts = [list_in.count(value) for value in set(list_in)]
    counts_dict = dict(zip(set(list_in), counts))
    return counts_dict
    
    
def smallest_multiple(n: int):
    """Returns the smallest positive number evenly divisible by integers from 1 to n"""
    factor_counts = [value_counts(prime_factors(i)) for i in range(2, n + 1)]
    combined = {k: max(d.get(k, 0) for d in factor_counts) for k in range(2, n + 1)}
    multiples = [pair[0] ** pair[1] for pair in combined.items()]
    product = np.product(multiples)
    return product


smallest_multiple(20)

232792560

### 6. Sum square difference

The sum of the squares of the first ten natural numbers is,
    
$1^2 + 2^2 + ... + 10^2 = 385$

The square of the sum of the first ten natural numbers is,
    
$(1 + 2 + ... + 10)^2 = 55^2 = 3025$

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is $3025 − 385 = 2640$.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [27]:
def sum_square_difference(n):
    """Returns the difference between the square of the sum and the sum of the squares of integers 1 to n"""
    sum_squares = sum(np.array(range(1, n + 1)) ** 2)
    square_sum = sum(range(1, n + 1)) ** 2
    return square_sum - sum_squares
    
sum_square_difference(100)

25164150

### 7. 10001st prime

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [2]:
def sieve_of_eratosthenes(n: int):
    """Uses the Sieve of Eratosthenes to return a list of all the prime numbers up to n"""
    A = [True] * (n - 1) # Boolean list with elements indexed from 2 to n
    for i in range(2, int(n ** 0.5) + 1): # Check numbers up to square root of ceiling
        if A[i - 2] is True: # If a number is currently marked as prime:
            for j in range(i ** 2, n + 1, i): # Mark all the multiples of it up to n as nonprime
                A[j - 2] = False
    primes = [i + 2 for i, x in enumerate(A) if x]
    return primes
sieve_of_eratosthenes(999999)[10000]

104743

### 8. Largest product in a series

The four adjacent digits in the 1000-digit number that have the greatest product are $9 × 9 × 8 × 9 = 5832$.

    73167176531330624919225119674426574742355349194934
    96983520312774506326239578318016984801869478851843
    85861560789112949495459501737958331952853208805511
    12540698747158523863050715693290963295227443043557
    66896648950445244523161731856403098711121722383113
    62229893423380308135336276614282806444486645238749
    30358907296290491560440772390713810515859307960866
    70172427121883998797908792274921901699720888093776
    65727333001053367881220235421809751254540594752243
    52584907711670556013604839586446706324415722155397
    53697817977846174064955149290862569321978468622482
    83972241375657056057490261407972968652414535100474
    82166370484403199890008895243450658541227588666881
    16427171479924442928230863465674813919123162824586
    17866458359124566529476545682848912883142607690042
    24219022671055626321111109370544217506941658960408
    07198403850962455444362981230987879927244284909188
    84580156166097919133875499200524063689912560717606
    05886116467109405077541002256983155200055935729725
    71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [29]:
q8_str = "7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450"

In [31]:
def largest_series_product(series: str, n: int):
    """Find the largest product of n adjacent digits in a string"""
    chunks = [list(series[i:i + n]) for i in range(len(series) - n + 1)]
    products = [np.product([int(i) for i in chunk]) for chunk in chunks]
    return max(products)
largest_series_product(q8_str, 13)

2091059712

### 9. Special Pythagorean triplet

A Pythagorean triplet is a set of three natural numbers, $a < b < c$, for which,
$a^2 + b^2 = c^2$

For example, $3^2 + 4^2 = 9 + 16 = 25 = 5^2$.

There exists exactly one Pythagorean triplet for which $a + b + c = 1000$.
Find the product $abc$.

In [62]:
def pythagorean_triplet(total: int):
    """Find a Pythagorean triplet that sums to total"""
    for m in range(1, total // 2):
        for n in range(1, m - 1):
            if (m * (m + n)) == (total / 2):
                return [m**2 - n**2, 2 * m * n, m**2 + n**2]
            
    return "None found"
np.prod(pythagorean_triplet(1000))

31875000

### 10. Summation of primes

The sum of the primes below $10$ is $2 + 3 + 5 + 7 = 17$.

Find the sum of all the primes below two million.

In [3]:
sum(sieve_of_eratosthenes(2000000))

142913828922

### 11. Largest product in a grid
In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

```
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
```

The product of these numbers is $26 × 63 × 78 × 14 = 1788696$.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [48]:
q11_grid = np.loadtxt('q11.txt')
p = []
for m in range(16):
    for n in range(16):
        four = q11_grid[m:m+4, n:n+4]
        p.append(np.prod(four[0, 0:4]))
        p.append(np.prod(four[0:4, 0]))
        p.append(np.prod(np.diag(four)))
        p.append(np.prod(np.diag(np.flip(four, axis=0))))
max(p)

70600674.0

### 12. Highly divisible triangular number
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [91]:
def num_divisors(i: int):
    """Find the number of divisors for an integer i"""
    pf = prime_factors(i)
    exponents = [len(list(v)) +1 for k, v in itertools.groupby(pf)]
    return int(np.prod(exponents))

def triangle(n: int, all=True):
    """Find the first n triangle numbers. If all=False, return only the nth"""
    triangles = list(itertools.accumulate(range(1, n + 1), func=operator.add))
    if all:
        return triangles
    else:
        return triangles[-1]

q12_df = pd.DataFrame({'triangle': triangle(20000)})
q12_df['divisors'] = q12_df.triangle.apply(num_divisors)
q12_df.loc[q12_df.divisors >= 500]

        triangle  divisors
12374   76576500       576
14398  103672800       648
16574  137373600       576
17198  147911400       576
18094  163723560       512

### 13. Large sum
Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

In [96]:
q13_nums = np.loadtxt('q13.txt')
np.sum(q13_nums)

5.5373762303908766e+51

### 14. Longest Collatz sequence


The following iterative sequence is defined for the set of positive integers:

$$n → n/2 \text{ (n is even)}$$

$$n → 3n + 1 \text{ (n is odd)}$$

Using the rule above and starting with 13, we generate the following sequence:
$$13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1$$

It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

In [100]:
def collatz(i: int):
    """Return the Collatz sequence starting at i"""
    def step(x):
        if x % 2 == 0:
            return x // 2
        else:
            return (3 * x) + 1
    sequence = []
    while i != 1:
        sequence.append(i)
        i = step(i)
    sequence.append(1)
    return(sequence)
q14_df = pd.DataFrame({'start': list(range(1, 1000001))})
q14_df['length'] = q14_df.start.apply(lambda x: len(collatz(x)))
q14_df.sort_values(by='length', ascending=False).head()

         start  length
837798  837799     525
626330  626331     509
939496  939497     507
704622  704623     504
910106  910107     476

### 15. Lattice paths
Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20×20 grid?

In [105]:
def n_choose_k(n,k):
    f = math.factorial
    return f(n) // f(k) // f(n-k)
n_choose_k(40, 20)

137846528820

### 16. Power digit sum
$2^{15} = 32768$ and the sum of its digits is $3 + 2 + 7 + 6 + 8 = 26$.

What is the sum of the digits of the number $2^{1000}$?

In [107]:
def digit_sum(i):
    digits = [int(d) for d in str(i)]
    return sum(digits)
digit_sum(2 ** 1000)

1366

### 17. Number letter counts
If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are $3 + 3 + 5 + 4 + 4 = 19$ letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?

NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

### 18. Maximum path sum I
By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

    3
    7 4
    2 4 6
    8 5 9 3

That is, $3 + 7 + 4 + 9 = 23$.

Find the maximum total from top to bottom of the triangle below:

    75
    95 64
    17 47 82
    18 35 87 10
    20 04 82 47 65
    19 01 23 75 03 34
    88 02 77 73 07 63 67
    99 65 04 28 06 16 70 92
    41 41 26 56 83 40 80 70 33
    41 48 72 33 47 32 37 16 94 29
    53 71 44 65 25 43 91 52 97 51 14
    70 11 33 28 77 73 17 78 39 68 17 57
    91 71 52 38 17 14 91 43 58 50 27 29 48
    63 66 04 68 89 53 67 30 73 16 69 87 40 31
    04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)

In [209]:
with open('q18.txt') as f:
    q18_nums = [line.rstrip().split(" ") for line in f.readlines()]
q18_nums = [[int(num) for num in line] for line in q18_nums]

In [210]:
def max_path_sum(lines):
    """Reduce a triangle grid by finding the max sum in the top row"""
    groups = []
    line0_i = range(len(lines[0]))
    line1_i = range(len(lines[1]))
    for index in line1_i:
        group = []
        for offset in [-1, 0]:
            if index + offset in line0_i:
                group.append((lines[1][index], lines[0][index + offset]))
        groups.append(group)
    max_sums = [max([sum(pair) for pair in group]) for group in groups]
    lines[1] = max_sums
    lines = lines[1:]
    return lines
while len(q18_nums) > 1:
    q18_nums = max_path_sum(q18_nums)
max(q18_nums[0])

1074

### 19. Counting Sundays
You are given the following information, but you may prefer to do some research for yourself.

* 1 Jan 1900 was a Monday.
* Thirty days has September,
    April, June and November.
    All the rest have thirty-one,
    Saving February alone,
    Which has twenty-eight, rain or shine.
    And on leap years, twenty-nine.
* A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.

How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?

In [266]:
[datetime.date(y, m, 1).weekday() for y in range(1901, 2001) for m in range(1, 13)].count(6)

171

### 20. Factorial digit sum
$n!$ means $n × (n − 1) × ... × 3 × 2 × 1$

For example, $10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800$,
and the sum of the digits in the number $10!$ is $3 + 6 + 2 + 8 + 8 + 0 + 0 = 27$.

Find the sum of the digits in the number $100!$

In [224]:
sum([int(d) for d in str(math.factorial(100))])

648

### 21. Amicable numbers
Let $d(n)$ be defined as the sum of proper divisors of $n$ (numbers less than $n$ which divide evenly into $n$).
If $d(a) = b$ and $d(b) = a$, where $a ≠ b$, then $a$ and $b$ are an amicable pair and each of $a$ and $b$ are called amicable numbers.

For example, the proper divisors of $220$ are $1, 2, 4, 5, 10, 11, 20, 22, 44, 55$ and $110$; therefore $d(220) = 284$. The proper divisors of $284$ are $1, 2, 4, 71$ and $142$; so $d(284) = 220$.

Evaluate the sum of all the amicable numbers under $10000$.

In [25]:
def divisors(n: int):
    """Return a list of the unique divisors of an integer"""
    pf = prime_factors(n)
    divs = []
    for r in range(1, len(pf) + 1):
        divs += [np.prod(comb) for comb in itertools.combinations(pf, r)]
    divs = list(set(divs))
    if n in divs:
        divs.remove(n)
    return [1] + divs

def amicable(a: int):
    """Check if a number is amicable, and if so return its pair."""
    b = sum(divisors(a))
    if a == sum(divisors(b)) and a != b:
        return a, b

sum(set(num for pair in [amicable(i) for i in range(2, 10000) if amicable(i) is not None] for num in pair))

31626

### 22. Names scores

Using names.txt (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.

For example, when the list is sorted into alphabetical order, COLIN, which is worth $3 + 15 + 12 + 9 + 14 = 53$, is the 938th name in the list. So, COLIN would obtain a score of $938 × 53 = 49714$.

What is the total of all the name scores in the file?

In [57]:
with open('q22.txt') as f:
    q22_names = f.read().strip('"').split('","')
q22_names.sort()

In [66]:
def name_score(name):
    alphabet_dict = {l: n for l, n in zip(list(string.ascii_uppercase), range(1, 27))}
    return sum([alphabet_dict.get(letter) for letter in name])

np.sum(np.array([name_score(name) for name in q22_names]) * np.array(range(1, len(q22_names) + 1)))

871198282

### 23. Non-abundant sums
A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of $28$ would be $1 + 2 + 4 + 7 + 14 = 28$, which means that $28$ is a perfect number.

A number $n$ is called deficient if the sum of its proper divisors is less than $n$ and it is called abundant if this sum exceeds $n$.

As $12$ is the smallest abundant number, $1 + 2 + 3 + 4 + 6 = 16$, the smallest number that can be written as the sum of two abundant numbers is $24$. By mathematical analysis, it can be shown that all integers greater than $28123$ can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.

Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.

In [83]:
def abundant(n: int):
    """Return a list of all abundant numbers up to n"""
    return [i for i in range(1, n + 1) if sum(divisors(i)) > i]

def non_abundant_sum(n: int):
    """Return a list of all numbers that cannot be written as the sum of two abundant numbers up to n"""
    abundant_sums = [sum(pair) for pair in itertools.combinations_with_replacement(abundant(n), 2)]
    non_abundant_sums = list(set(range(1, n + 1)) - set(abundant_sums))
    return non_abundant_sums
sum(non_abundant_sum(28123))

4179871

### 24. Lexicographic permutations
A permutation is an ordered arrangement of objects. For example, $3124$ is one possible permutation of the digits $1, 2, 3$ and $4$. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of $0, 1$ and $2$ are:

    012   021   102   120   201   210

What is the millionth lexicographic permutation of the digits $0, 1, 2, 3, 4, 5, 6, 7, 8$ and $9$?

In [97]:
int("".join(next(itertools.islice(itertools.permutations('0123456789'), 999999, 1000000))))

2783915460

### 25. 1000-digit Fibonacci number

The Fibonacci sequence is defined by the recurrence relation:

    Fn = Fn−1 + Fn−2, where F1 = 1 and F2 = 1.

Hence the first 12 terms will be:

    F1 = 1
    F2 = 1
    F3 = 2
    F4 = 3
    F5 = 5
    F6 = 8
    F7 = 13
    F8 = 21
    F9 = 34
    F10 = 55
    F11 = 89
    F12 = 144

The 12th term, F12, is the first term to contain three digits.

What is the index of the first term in the Fibonacci sequence to contain 1000 digits?

In [99]:
sys.maxint

NameError: name 'sys' is not defined

### 28. Number spiral diagonals

Starting with the number 1 and moving to the right in a clockwise direction a 5 by 5 spiral is formed as follows:
```
21 22 23 24 25
20  7  8  9 10
19  6  1  2 11
18  5  4  3 12
17 16 15 14 13
```
It can be verified that the sum of the numbers on the diagonals is 101.

What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?

In [132]:
def number_spiral(spiral_size):
    def ring_sum(side_length):
        ring_num = (side_length + 1) // 2
        ne_corner = side_length ** 2
        return (4 * ne_corner) - (6 * side_length) + 6
    return 1 + sum([ring_sum(side) for side in range(3, spiral_size + 1, 2)])
number_spiral(1001)

669171001

### 30. Digit fifth powers
Surprisingly there are only three numbers that can be written as the sum of fourth powers of their digits:

$$1634 = 14 + 64 + 34 + 44$$
$$8208 = 84 + 24 + 04 + 84$$
$$9474 = 94 + 44 + 74 + 44$$

As 1 = 14 is not a sum it is not included.

The sum of these numbers is $1634 + 8208 + 9474 = 19316$.

Find the sum of all the numbers that can be written as the sum of fifth powers of their digits.

In [139]:
def digit_power(i: int, p: int):
    """Calculate the sum of the digits of a number i raised to power p"""
    return sum([int(d) ** p for d in str(i)])
sum([i for i in range(2, 1000000) if digit_power(i, 5) == i])

443839

### 31. Coin sums

In England the currency is made up of pound, £, and pence, p, and there are eight coins in general circulation:

$$1p, 2p, 5p, 10p, 20p, 50p, £1 (100p), £2 (200p).$$

It is possible to make £2 in the following way:

$$1×£1 + 1×50p + 2×20p + 1×5p + 1×2p + 3×1p$$

How many different ways can £2 be made using any number of coins?

In [203]:
def coin_sum(total, coins):
    coins.sort(reverse=True)
    for coin in coins:
        for count in range((total // coin) + 1)
    return coins
coin_sum(5, [1, 2, 5])

[5, 2, 1]

In [201]:
def coin_sum(total):
    coins = (1, 2, 5, 10, 20, 50, 100, 200)
    coin_dict = {coin: range((total // coin) + 1) for coin in coins}
    def comb_generator(coin_list, count_generator):
        for count in count_generator:
            coin_comb = list(zip(coin_list, count))
            coin_sum = sum([coin * count for coin, count in coin_comb])
            if coin_sum == total:
                yield coin_comb
    coin_combs = comb_generator(coins, itertools.product(*coin_dict.values()))
    return list(coin_combs)
len(coin_sum(200))

KeyboardInterrupt:

### 33. Digit cancelling fractions

The fraction $\frac{49}{98}$ is a curious fraction, as an inexperienced mathematician in attempting to simplify it may incorrectly believe that $\frac{49}{98}$ = $\frac{4}{8}$, which is correct, is obtained by cancelling the 9s.

We shall consider fractions like, $\frac{30}{50}$ = $\frac{30}{50}$, to be trivial examples.

There are exactly four non-trivial examples of this type of fraction, less than one in value, and containing two digits in the numerator and denominator.

If the product of these four fractions is given in its lowest common terms, find the value of the denominator.

In [204]:
def digit_cancelling_fractions(digits: int=2):
    for denom in range(10, 100):
        for numer in range(10, denom):
            if any()

SyntaxError: unexpected EOF while parsing (<ipython-input-204-a2422c1dcffd>, line 2)

In [211]:
[d in 'ab' for d in 'bc']

[True, False]

### 34. Digit factorials
$145$ is a curious number, as $1! + 4! + 5! = 1 + 24 + 120 = 145$.

Find the sum of all numbers which are equal to the sum of the factorial of their digits.

Note: as $1! = 1$ and $2! = 2$ are not sums they are not included.

In [222]:
def digit_factorial(i: int):
    """Calculate the sum of the factorial of the digits of a number"""
    return sum([math.factorial(int(d)) for d in str(i)])
total = 0
for i in range(10, 10000000):
    if digit_factorial(i) == i:
        total += i
total

40730

### 35. Circular primes

The number, 197, is called a circular prime because all rotations of the digits: 197, 971, and 719, are themselves prime.

There are thirteen such primes below 100: 2, 3, 5, 7, 11, 13, 17, 31, 37, 71, 73, 79, and 97.

How many circular primes are there below one million?

In [50]:
def rotate_digits(i):
    str_num = str(i)
    rotateds = [str_num]
    for i in range(len(str_num) - 1):
        last_num = rotateds[-1]
        next_num = last_num[1:] + last_num[:1]
        rotateds.append(next_num)
    return [int(i) for i in rotateds]

rotate_digits(197)

[197, 971, 719]

In [49]:
def circular_primes(threshold: int):
    primes = sieve_of_eratosthenes(threshold)
    circulars = set()
    for i in primes:
        rotations = rotate_digits(i)
        if all(rot in primes for rot in rotations):
            circulars = circulars | set(rotations)
    return circulars

len(circular_primes(1000000))

55

### 36. Double-base palindromes


The decimal number, 585 = 1001001001 (binary), is palindromic in both bases.

Find the sum of all numbers, less than one million, which are palindromic in base 10 and base 2.

(Please note that the palindromic number, in either base, may not include leading zeros.)

In [65]:
def db_palindromes(threshold: int):
    for i in range(1, threshold):
        decimal = str(i)
        binary = f'{i:b}'
        if decimal == decimal[::-1] and binary == binary[::-1]:
            yield i

sum(db_palindromes(1000000))

872187

### 37. Truncatable primes

The number 3797 has an interesting property. Being prime itself, it is possible to continuously remove digits from left to right, and remain prime at each stage: 3797, 797, 97, and 7. Similarly we can work from right to left: 3797, 379, 37, and 3.

Find the sum of the only eleven primes that are both truncatable from left to right and right to left.

NOTE: 2, 3, 5, and 7 are not considered to be truncatable primes.

In [13]:
def truncatable_primes():
    primes = sieve_of_eratosthenes(1000000)
    out = []
    for p in primes:
        string_p = str(p)
        truncs = [string_p]
        for i in range(1, len(string_p)):
            truncs.append(string_p[i:])
            truncs.append(string_p[:-i])
        if all(int(t) in primes for t in truncs):
            yield p
# truncatable_primes()
list(truncatable_primes())

[2, 3, 5, 7, 23, 37, 53, 73, 313, 317, 373, 797, 3137, 3797, 739397]

In [18]:
sum([2, 3, 5, 7, 23, 37, 53, 73, 313, 317, 373, 797, 3137, 3797, 739397][4:])

748317

### 40. Champernowne's constant

An irrational decimal fraction is created by concatenating the positive integers:

$$0.123456789101112131415161718192021...$$

It can be seen that the 12th digit of the fractional part is 1.

If $d_n$ represents the nth digit of the fractional part, find the value of the following expression.

$$d_1 × d_{10} × d_{100} × d_{1000} × d_{10000} × d_{100000} × d_{1000000}$$

### 67. Maximum path sum II
By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

    3
    7 4
    2 4 6
    8 5 9 3

That is, $3 + 7 + 4 + 9 = 23$.

Find the maximum total from top to bottom in triangle.txt (right click and 'Save Link/Target As...'), a 15K text file containing a triangle with one-hundred rows.

NOTE: This is a much more difficult version of Problem 18. It is not possible to try every route to solve this problem, as there are 299 altogether! If you could check one trillion ($10^(12)$) routes every second it would take over twenty billion years to check them all. There is an efficient algorithm to solve it. ;o)

In [213]:
with open('q67.txt') as f:
    q67_nums = [line.rstrip().split(" ") for line in f.readlines()]
q67_nums = [[int(num) for num in line] for line in q67_nums]

In [215]:
while len(q67_nums) > 1:
    q67_nums = max_path_sum(q67_nums)
max(q67_nums[0])

7273